import type { AppTheme, DesignPresetId } from '@/src/theme/types';

const baseSpacing = { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 };
const baseRadius = { sm: 8, md: 12, lg: 16, xl: 24 };

export const DESIGN_PRESETS: Record<DesignPresetId, AppTheme> = {
  trustTeal: {
    id: 'trustTeal',
    name: 'Trust Teal',
    tagline: 'Clean and trustworthy — great default',
    colors: {
      primary: '#0d9488',
      primarySoft: '#ccfbf1',
      background: '#f0fdfa',
      backgroundAlt: '#ecfeff',
      surface: '#ffffff',
      surfaceMuted: '#f8fafc',
      text: '#0f172a',
      textSecondary: '#64748b',
      textOnPrimary: '#ffffff',
      border: '#e2e8f0',
      accent: '#0284c7',
      danger: '#dc2626',
      headerBg: '#0f766e',
      tabBar: '#ffffff',
      tabBarBorder: '#e2e8f0',
      ratingHigh: '#16a34a',
      ratingMid: '#ca8a04',
      ratingLow: '#dc2626',
      ratingNone: '#94a3b8',
    },
    radius: baseRadius,
    spacing: baseSpacing,
  },
  midnightAmber: {
    id: 'midnightAmber',
    name: 'Midnight Amber',
    tagline: 'Bold dark mode — easy on the eyes at night',
    colors: {
      primary: '#f59e0b',
      primarySoft: '#422006',
      background: '#0f172a',
      backgroundAlt: '#1e293b',
      surface: '#1e293b',
      surfaceMuted: '#334155',
      text: '#f8fafc',
      textSecondary: '#94a3b8',
      textOnPrimary: '#0f172a',
      border: '#334155',
      accent: '#38bdf8',
      danger: '#f87171',
      headerBg: '#020617',
      tabBar: '#0f172a',
      tabBarBorder: '#334155',
      ratingHigh: '#4ade80',
      ratingMid: '#fbbf24',
      ratingLow: '#f87171',
      ratingNone: '#64748b',
    },
    radius: baseRadius,
    spacing: baseSpacing,
  },
  softPaper: {
    id: 'softPaper',
    name: 'Soft Paper',
    tagline: 'Warm and readable — review-first layout',
    colors: {
      primary: '#b45309',
      primarySoft: '#ffedd5',
      background: '#fffbeb',
      backgroundAlt: '#fef3c7',
      surface: '#ffffff',
      surfaceMuted: '#fff7ed',
      text: '#292524',
      textSecondary: '#78716c',
      textOnPrimary: '#ffffff',
      border: '#e7e5e4',
      accent: '#0d9488',
      danger: '#b91c1c',
      headerBg: '#92400e',
      tabBar: '#fffbeb',
      tabBarBorder: '#e7e5e4',
      ratingHigh: '#15803d',
      ratingMid: '#a16207',
      ratingLow: '#b91c1c',
      ratingNone: '#a8a29e',
    },
    radius: baseRadius,
    spacing: baseSpacing,
  },
};

export const DEFAULT_PRESET_ID: DesignPresetId = 'trustTeal';

export const PRESET_LIST = Object.values(DESIGN_PRESETS);
